project_id = "wekkwrhyaoiyohzdztdg"
[functions.syrve-connect-test]
enabled = true
verify_jwt = true
import_map = "./functions/syrve-connect-test/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/syrve-connect-test/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/syrve-connect-test/*.html" ]

[functions.syrve-product-sync]
enabled = true
verify_jwt = true
import_map = "./functions/syrve-product-sync/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/syrve-product-sync/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/syrve-product-sync/*.html" ]
